/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientPortalIndexRouteImport } from './routes/client-portal/index'
import { Route as ClientPortalTokenRouteImport } from './routes/client-portal/$token'
import { Route as AuthenticatedTicketsRouteImport } from './routes/_authenticated/tickets'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedHrRouteImport } from './routes/_authenticated/hr'
import { Route as AuthenticatedDocsRouteImport } from './routes/_authenticated/docs'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedTicketsIndexRouteImport } from './routes/_authenticated/tickets/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedInvoicesIndexRouteImport } from './routes/_authenticated/invoices/index'
import { Route as AuthenticatedHrIndexRouteImport } from './routes/_authenticated/hr/index'
import { Route as AuthenticatedCrmIndexRouteImport } from './routes/_authenticated/crm/index'
import { Route as AuthenticatedAnalyticsIndexRouteImport } from './routes/_authenticated/analytics/index'
import { Route as AuthenticatedTicketsNewRouteImport } from './routes/_authenticated/tickets/new'
import { Route as AuthenticatedTicketsTicketIdRouteImport } from './routes/_authenticated/tickets/$ticketId'
import { Route as AuthenticatedSettingsTeamRouteImport } from './routes/_authenticated/settings/team'
import { Route as AuthenticatedSettingsSecurityRouteImport } from './routes/_authenticated/settings/security'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings/profile'
import { Route as AuthenticatedSettingsPreferencesRouteImport } from './routes/_authenticated/settings/preferences'
import { Route as AuthenticatedSettingsOrganizationRouteImport } from './routes/_authenticated/settings/organization'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsModulesRouteImport } from './routes/_authenticated/settings/modules'
import { Route as AuthenticatedSettingsDataRouteImport } from './routes/_authenticated/settings/data'
import { Route as AuthenticatedSettingsBillingRouteImport } from './routes/_authenticated/settings/billing'
import { Route as AuthenticatedProjectsNewRouteImport } from './routes/_authenticated/projects/new'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects/$projectId'
import { Route as AuthenticatedInvoicesNewRouteImport } from './routes/_authenticated/invoices/new'
import { Route as AuthenticatedInvoicesInvoiceIdRouteImport } from './routes/_authenticated/invoices/$invoiceId'
import { Route as AuthenticatedHrSettingsRouteImport } from './routes/_authenticated/hr/settings'
import { Route as AuthenticatedHrReportsRouteImport } from './routes/_authenticated/hr/reports'
import { Route as AuthenticatedDocsTrashRouteImport } from './routes/_authenticated/docs/trash'
import { Route as AuthenticatedDocsSettingsRouteImport } from './routes/_authenticated/docs/settings'
import { Route as AuthenticatedDocsRecentRouteImport } from './routes/_authenticated/docs/recent'
import { Route as AuthenticatedDocsFavoritesRouteImport } from './routes/_authenticated/docs/favorites'
import { Route as AuthenticatedDocsActivityRouteImport } from './routes/_authenticated/docs/activity'
import { Route as AuthenticatedAnalyticsSettingsRouteImport } from './routes/_authenticated/analytics/settings'
import { Route as AuthenticatedAnalyticsReportsRouteImport } from './routes/_authenticated/analytics/reports'
import { Route as AuthenticatedAnalyticsGoalsRouteImport } from './routes/_authenticated/analytics/goals'
import { Route as AuthenticatedAnalyticsDashboardsRouteImport } from './routes/_authenticated/analytics/dashboards'
import { Route as ClientPortalProjectProjectIdIndexRouteImport } from './routes/client-portal/project/$projectId/index'
import { Route as AuthenticatedTicketsStatsIndexRouteImport } from './routes/_authenticated/tickets/stats/index'
import { Route as AuthenticatedTicketsSettingsIndexRouteImport } from './routes/_authenticated/tickets/settings/index'
import { Route as AuthenticatedTicketsKnowledgeBaseIndexRouteImport } from './routes/_authenticated/tickets/knowledge-base/index'
import { Route as AuthenticatedTicketsInboxIndexRouteImport } from './routes/_authenticated/tickets/inbox/index'
import { Route as AuthenticatedTicketsAutomationsIndexRouteImport } from './routes/_authenticated/tickets/automations/index'
import { Route as AuthenticatedProjectsTimeIndexRouteImport } from './routes/_authenticated/projects/time/index'
import { Route as AuthenticatedProjectsKanbanIndexRouteImport } from './routes/_authenticated/projects/kanban/index'
import { Route as AuthenticatedProjectsGanttIndexRouteImport } from './routes/_authenticated/projects/gantt/index'
import { Route as AuthenticatedInvoicesSettingsIndexRouteImport } from './routes/_authenticated/invoices/settings/index'
import { Route as AuthenticatedInvoicesQuotesIndexRouteImport } from './routes/_authenticated/invoices/quotes/index'
import { Route as AuthenticatedInvoicesProductsIndexRouteImport } from './routes/_authenticated/invoices/products/index'
import { Route as AuthenticatedInvoicesClientsIndexRouteImport } from './routes/_authenticated/invoices/clients/index'
import { Route as AuthenticatedHrTimeTrackingIndexRouteImport } from './routes/_authenticated/hr/time-tracking/index'
import { Route as AuthenticatedHrLeavesIndexRouteImport } from './routes/_authenticated/hr/leaves/index'
import { Route as AuthenticatedHrInterviewsIndexRouteImport } from './routes/_authenticated/hr/interviews/index'
import { Route as AuthenticatedHrAlertsIndexRouteImport } from './routes/_authenticated/hr/alerts/index'
import { Route as AuthenticatedCrmPipelineIndexRouteImport } from './routes/_authenticated/crm/pipeline/index'
import { Route as AuthenticatedCrmContactsIndexRouteImport } from './routes/_authenticated/crm/contacts/index'
import { Route as AuthenticatedCrmCompaniesIndexRouteImport } from './routes/_authenticated/crm/companies/index'
import { Route as AuthenticatedCrmActivitiesIndexRouteImport } from './routes/_authenticated/crm/activities/index'
import { Route as AuthenticatedSettingsModulesCompareRouteImport } from './routes/_authenticated/settings/modules.compare'
import { Route as AuthenticatedInvoicesQuotesNewRouteImport } from './routes/_authenticated/invoices/quotes/new'
import { Route as AuthenticatedInvoicesQuotesQuoteIdRouteImport } from './routes/_authenticated/invoices/quotes/$quoteId'
import { Route as AuthenticatedInvoicesProductsNewRouteImport } from './routes/_authenticated/invoices/products/new'
import { Route as AuthenticatedInvoicesClientsNewRouteImport } from './routes/_authenticated/invoices/clients/new'
import { Route as AuthenticatedInvoicesClientsClientIdRouteImport } from './routes/_authenticated/invoices/clients/$clientId'
import { Route as AuthenticatedHrEmployeesNewRouteImport } from './routes/_authenticated/hr/employees/new'
import { Route as AuthenticatedHrEmployeesEmployeeIdRouteImport } from './routes/_authenticated/hr/employees/$employeeId'
import { Route as AuthenticatedDocsFolderFolderIdRouteImport } from './routes/_authenticated/docs/folder/$folderId'
import { Route as AuthenticatedDocsFileFileIdRouteImport } from './routes/_authenticated/docs/file/$fileId'
import { Route as AuthenticatedCrmContactsNewRouteImport } from './routes/_authenticated/crm/contacts/new'
import { Route as AuthenticatedCrmContactsContactIdRouteImport } from './routes/_authenticated/crm/contacts/$contactId'
import { Route as AuthenticatedCrmCompaniesNewRouteImport } from './routes/_authenticated/crm/companies/new'
import { Route as AuthenticatedCrmCompaniesCompanyIdRouteImport } from './routes/_authenticated/crm/companies/$companyId'
import { Route as AuthenticatedAnalyticsDashboardDashboardIdRouteImport } from './routes/_authenticated/analytics/dashboard/$dashboardId'
import { Route as AuthenticatedProjectsProjectIdClientPortalIndexRouteImport } from './routes/_authenticated/projects/$projectId/client-portal/index'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientPortalIndexRoute = ClientPortalIndexRouteImport.update({
  id: '/client-portal/',
  path: '/client-portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientPortalTokenRoute = ClientPortalTokenRouteImport.update({
  id: '/client-portal/$token',
  path: '/client-portal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTicketsRoute = AuthenticatedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHrRoute = AuthenticatedHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocsRoute = AuthenticatedDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTicketsIndexRoute =
  AuthenticatedTicketsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTicketsRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const AuthenticatedInvoicesIndexRoute =
  AuthenticatedInvoicesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedInvoicesRoute,
  } as any)
const AuthenticatedHrIndexRoute = AuthenticatedHrIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedHrRoute,
} as any)
const AuthenticatedCrmIndexRoute = AuthenticatedCrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const AuthenticatedAnalyticsIndexRoute =
  AuthenticatedAnalyticsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAnalyticsRoute,
  } as any)
const AuthenticatedTicketsNewRoute = AuthenticatedTicketsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedTicketsRoute,
} as any)
const AuthenticatedTicketsTicketIdRoute =
  AuthenticatedTicketsTicketIdRouteImport.update({
    id: '/$ticketId',
    path: '/$ticketId',
    getParentRoute: () => AuthenticatedTicketsRoute,
  } as any)
const AuthenticatedSettingsTeamRoute =
  AuthenticatedSettingsTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsSecurityRoute =
  AuthenticatedSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsPreferencesRoute =
  AuthenticatedSettingsPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsOrganizationRoute =
  AuthenticatedSettingsOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsModulesRoute =
  AuthenticatedSettingsModulesRouteImport.update({
    id: '/modules',
    path: '/modules',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsDataRoute =
  AuthenticatedSettingsDataRouteImport.update({
    id: '/data',
    path: '/data',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsBillingRoute =
  AuthenticatedSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedProjectsNewRoute =
  AuthenticatedProjectsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const AuthenticatedInvoicesNewRoute =
  AuthenticatedInvoicesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedInvoicesRoute,
  } as any)
const AuthenticatedInvoicesInvoiceIdRoute =
  AuthenticatedInvoicesInvoiceIdRouteImport.update({
    id: '/$invoiceId',
    path: '/$invoiceId',
    getParentRoute: () => AuthenticatedInvoicesRoute,
  } as any)
const AuthenticatedHrSettingsRoute = AuthenticatedHrSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedHrRoute,
} as any)
const AuthenticatedHrReportsRoute = AuthenticatedHrReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedHrRoute,
} as any)
const AuthenticatedDocsTrashRoute = AuthenticatedDocsTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AuthenticatedDocsRoute,
} as any)
const AuthenticatedDocsSettingsRoute =
  AuthenticatedDocsSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDocsRoute,
  } as any)
const AuthenticatedDocsRecentRoute = AuthenticatedDocsRecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => AuthenticatedDocsRoute,
} as any)
const AuthenticatedDocsFavoritesRoute =
  AuthenticatedDocsFavoritesRouteImport.update({
    id: '/favorites',
    path: '/favorites',
    getParentRoute: () => AuthenticatedDocsRoute,
  } as any)
const AuthenticatedDocsActivityRoute =
  AuthenticatedDocsActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedDocsRoute,
  } as any)
const AuthenticatedAnalyticsSettingsRoute =
  AuthenticatedAnalyticsSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAnalyticsRoute,
  } as any)
const AuthenticatedAnalyticsReportsRoute =
  AuthenticatedAnalyticsReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAnalyticsRoute,
  } as any)
const AuthenticatedAnalyticsGoalsRoute =
  AuthenticatedAnalyticsGoalsRouteImport.update({
    id: '/goals',
    path: '/goals',
    getParentRoute: () => AuthenticatedAnalyticsRoute,
  } as any)
const AuthenticatedAnalyticsDashboardsRoute =
  AuthenticatedAnalyticsDashboardsRouteImport.update({
    id: '/dashboards',
    path: '/dashboards',
    getParentRoute: () => AuthenticatedAnalyticsRoute,
  } as any)
const ClientPortalProjectProjectIdIndexRoute =
  ClientPortalProjectProjectIdIndexRouteImport.update({
    id: '/client-portal/project/$projectId/',
    path: '/client-portal/project/$projectId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedTicketsStatsIndexRoute =
  AuthenticatedTicketsStatsIndexRouteImport.update({
    id: '/stats/',
    path: '/stats/',
    getParentRoute: () => AuthenticatedTicketsRoute,
  } as any)
const AuthenticatedTicketsSettingsIndexRoute =
  AuthenticatedTicketsSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedTicketsRoute,
  } as any)
const AuthenticatedTicketsKnowledgeBaseIndexRoute =
  AuthenticatedTicketsKnowledgeBaseIndexRouteImport.update({
    id: '/knowledge-base/',
    path: '/knowledge-base/',
    getParentRoute: () => AuthenticatedTicketsRoute,
  } as any)
const AuthenticatedTicketsInboxIndexRoute =
  AuthenticatedTicketsInboxIndexRouteImport.update({
    id: '/inbox/',
    path: '/inbox/',
    getParentRoute: () => AuthenticatedTicketsRoute,
  } as any)
const AuthenticatedTicketsAutomationsIndexRoute =
  AuthenticatedTicketsAutomationsIndexRouteImport.update({
    id: '/automations/',
    path: '/automations/',
    getParentRoute: () => AuthenticatedTicketsRoute,
  } as any)
const AuthenticatedProjectsTimeIndexRoute =
  AuthenticatedProjectsTimeIndexRouteImport.update({
    id: '/time/',
    path: '/time/',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const AuthenticatedProjectsKanbanIndexRoute =
  AuthenticatedProjectsKanbanIndexRouteImport.update({
    id: '/kanban/',
    path: '/kanban/',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const AuthenticatedProjectsGanttIndexRoute =
  AuthenticatedProjectsGanttIndexRouteImport.update({
    id: '/gantt/',
    path: '/gantt/',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const AuthenticatedInvoicesSettingsIndexRoute =
  AuthenticatedInvoicesSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedInvoicesRoute,
  } as any)
const AuthenticatedInvoicesQuotesIndexRoute =
  AuthenticatedInvoicesQuotesIndexRouteImport.update({
    id: '/quotes/',
    path: '/quotes/',
    getParentRoute: () => AuthenticatedInvoicesRoute,
  } as any)
const AuthenticatedInvoicesProductsIndexRoute =
  AuthenticatedInvoicesProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedInvoicesRoute,
  } as any)
const AuthenticatedInvoicesClientsIndexRoute =
  AuthenticatedInvoicesClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedInvoicesRoute,
  } as any)
const AuthenticatedHrTimeTrackingIndexRoute =
  AuthenticatedHrTimeTrackingIndexRouteImport.update({
    id: '/time-tracking/',
    path: '/time-tracking/',
    getParentRoute: () => AuthenticatedHrRoute,
  } as any)
const AuthenticatedHrLeavesIndexRoute =
  AuthenticatedHrLeavesIndexRouteImport.update({
    id: '/leaves/',
    path: '/leaves/',
    getParentRoute: () => AuthenticatedHrRoute,
  } as any)
const AuthenticatedHrInterviewsIndexRoute =
  AuthenticatedHrInterviewsIndexRouteImport.update({
    id: '/interviews/',
    path: '/interviews/',
    getParentRoute: () => AuthenticatedHrRoute,
  } as any)
const AuthenticatedHrAlertsIndexRoute =
  AuthenticatedHrAlertsIndexRouteImport.update({
    id: '/alerts/',
    path: '/alerts/',
    getParentRoute: () => AuthenticatedHrRoute,
  } as any)
const AuthenticatedCrmPipelineIndexRoute =
  AuthenticatedCrmPipelineIndexRouteImport.update({
    id: '/pipeline/',
    path: '/pipeline/',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedCrmContactsIndexRoute =
  AuthenticatedCrmContactsIndexRouteImport.update({
    id: '/contacts/',
    path: '/contacts/',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedCrmCompaniesIndexRoute =
  AuthenticatedCrmCompaniesIndexRouteImport.update({
    id: '/companies/',
    path: '/companies/',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedCrmActivitiesIndexRoute =
  AuthenticatedCrmActivitiesIndexRouteImport.update({
    id: '/activities/',
    path: '/activities/',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedSettingsModulesCompareRoute =
  AuthenticatedSettingsModulesCompareRouteImport.update({
    id: '/compare',
    path: '/compare',
    getParentRoute: () => AuthenticatedSettingsModulesRoute,
  } as any)
const AuthenticatedInvoicesQuotesNewRoute =
  AuthenticatedInvoicesQuotesNewRouteImport.update({
    id: '/quotes/new',
    path: '/quotes/new',
    getParentRoute: () => AuthenticatedInvoicesRoute,
  } as any)
const AuthenticatedInvoicesQuotesQuoteIdRoute =
  AuthenticatedInvoicesQuotesQuoteIdRouteImport.update({
    id: '/quotes/$quoteId',
    path: '/quotes/$quoteId',
    getParentRoute: () => AuthenticatedInvoicesRoute,
  } as any)
const AuthenticatedInvoicesProductsNewRoute =
  AuthenticatedInvoicesProductsNewRouteImport.update({
    id: '/products/new',
    path: '/products/new',
    getParentRoute: () => AuthenticatedInvoicesRoute,
  } as any)
const AuthenticatedInvoicesClientsNewRoute =
  AuthenticatedInvoicesClientsNewRouteImport.update({
    id: '/clients/new',
    path: '/clients/new',
    getParentRoute: () => AuthenticatedInvoicesRoute,
  } as any)
const AuthenticatedInvoicesClientsClientIdRoute =
  AuthenticatedInvoicesClientsClientIdRouteImport.update({
    id: '/clients/$clientId',
    path: '/clients/$clientId',
    getParentRoute: () => AuthenticatedInvoicesRoute,
  } as any)
const AuthenticatedHrEmployeesNewRoute =
  AuthenticatedHrEmployeesNewRouteImport.update({
    id: '/employees/new',
    path: '/employees/new',
    getParentRoute: () => AuthenticatedHrRoute,
  } as any)
const AuthenticatedHrEmployeesEmployeeIdRoute =
  AuthenticatedHrEmployeesEmployeeIdRouteImport.update({
    id: '/employees/$employeeId',
    path: '/employees/$employeeId',
    getParentRoute: () => AuthenticatedHrRoute,
  } as any)
const AuthenticatedDocsFolderFolderIdRoute =
  AuthenticatedDocsFolderFolderIdRouteImport.update({
    id: '/folder/$folderId',
    path: '/folder/$folderId',
    getParentRoute: () => AuthenticatedDocsRoute,
  } as any)
const AuthenticatedDocsFileFileIdRoute =
  AuthenticatedDocsFileFileIdRouteImport.update({
    id: '/file/$fileId',
    path: '/file/$fileId',
    getParentRoute: () => AuthenticatedDocsRoute,
  } as any)
const AuthenticatedCrmContactsNewRoute =
  AuthenticatedCrmContactsNewRouteImport.update({
    id: '/contacts/new',
    path: '/contacts/new',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedCrmContactsContactIdRoute =
  AuthenticatedCrmContactsContactIdRouteImport.update({
    id: '/contacts/$contactId',
    path: '/contacts/$contactId',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedCrmCompaniesNewRoute =
  AuthenticatedCrmCompaniesNewRouteImport.update({
    id: '/companies/new',
    path: '/companies/new',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedCrmCompaniesCompanyIdRoute =
  AuthenticatedCrmCompaniesCompanyIdRouteImport.update({
    id: '/companies/$companyId',
    path: '/companies/$companyId',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedAnalyticsDashboardDashboardIdRoute =
  AuthenticatedAnalyticsDashboardDashboardIdRouteImport.update({
    id: '/dashboard/$dashboardId',
    path: '/dashboard/$dashboardId',
    getParentRoute: () => AuthenticatedAnalyticsRoute,
  } as any)
const AuthenticatedProjectsProjectIdClientPortalIndexRoute =
  AuthenticatedProjectsProjectIdClientPortalIndexRouteImport.update({
    id: '/client-portal/',
    path: '/client-portal/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/analytics': typeof AuthenticatedAnalyticsRouteWithChildren
  '/crm': typeof AuthenticatedCrmRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/docs': typeof AuthenticatedDocsRouteWithChildren
  '/hr': typeof AuthenticatedHrRouteWithChildren
  '/invoices': typeof AuthenticatedInvoicesRouteWithChildren
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/tickets': typeof AuthenticatedTicketsRouteWithChildren
  '/client-portal/$token': typeof ClientPortalTokenRoute
  '/client-portal/': typeof ClientPortalIndexRoute
  '/analytics/dashboards': typeof AuthenticatedAnalyticsDashboardsRoute
  '/analytics/goals': typeof AuthenticatedAnalyticsGoalsRoute
  '/analytics/reports': typeof AuthenticatedAnalyticsReportsRoute
  '/analytics/settings': typeof AuthenticatedAnalyticsSettingsRoute
  '/docs/activity': typeof AuthenticatedDocsActivityRoute
  '/docs/favorites': typeof AuthenticatedDocsFavoritesRoute
  '/docs/recent': typeof AuthenticatedDocsRecentRoute
  '/docs/settings': typeof AuthenticatedDocsSettingsRoute
  '/docs/trash': typeof AuthenticatedDocsTrashRoute
  '/hr/reports': typeof AuthenticatedHrReportsRoute
  '/hr/settings': typeof AuthenticatedHrSettingsRoute
  '/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/settings/data': typeof AuthenticatedSettingsDataRoute
  '/settings/modules': typeof AuthenticatedSettingsModulesRouteWithChildren
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/settings/preferences': typeof AuthenticatedSettingsPreferencesRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/tickets/$ticketId': typeof AuthenticatedTicketsTicketIdRoute
  '/tickets/new': typeof AuthenticatedTicketsNewRoute
  '/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/crm/': typeof AuthenticatedCrmIndexRoute
  '/hr/': typeof AuthenticatedHrIndexRoute
  '/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tickets/': typeof AuthenticatedTicketsIndexRoute
  '/analytics/dashboard/$dashboardId': typeof AuthenticatedAnalyticsDashboardDashboardIdRoute
  '/crm/companies/$companyId': typeof AuthenticatedCrmCompaniesCompanyIdRoute
  '/crm/companies/new': typeof AuthenticatedCrmCompaniesNewRoute
  '/crm/contacts/$contactId': typeof AuthenticatedCrmContactsContactIdRoute
  '/crm/contacts/new': typeof AuthenticatedCrmContactsNewRoute
  '/docs/file/$fileId': typeof AuthenticatedDocsFileFileIdRoute
  '/docs/folder/$folderId': typeof AuthenticatedDocsFolderFolderIdRoute
  '/hr/employees/$employeeId': typeof AuthenticatedHrEmployeesEmployeeIdRoute
  '/hr/employees/new': typeof AuthenticatedHrEmployeesNewRoute
  '/invoices/clients/$clientId': typeof AuthenticatedInvoicesClientsClientIdRoute
  '/invoices/clients/new': typeof AuthenticatedInvoicesClientsNewRoute
  '/invoices/products/new': typeof AuthenticatedInvoicesProductsNewRoute
  '/invoices/quotes/$quoteId': typeof AuthenticatedInvoicesQuotesQuoteIdRoute
  '/invoices/quotes/new': typeof AuthenticatedInvoicesQuotesNewRoute
  '/settings/modules/compare': typeof AuthenticatedSettingsModulesCompareRoute
  '/crm/activities/': typeof AuthenticatedCrmActivitiesIndexRoute
  '/crm/companies/': typeof AuthenticatedCrmCompaniesIndexRoute
  '/crm/contacts/': typeof AuthenticatedCrmContactsIndexRoute
  '/crm/pipeline/': typeof AuthenticatedCrmPipelineIndexRoute
  '/hr/alerts/': typeof AuthenticatedHrAlertsIndexRoute
  '/hr/interviews/': typeof AuthenticatedHrInterviewsIndexRoute
  '/hr/leaves/': typeof AuthenticatedHrLeavesIndexRoute
  '/hr/time-tracking/': typeof AuthenticatedHrTimeTrackingIndexRoute
  '/invoices/clients/': typeof AuthenticatedInvoicesClientsIndexRoute
  '/invoices/products/': typeof AuthenticatedInvoicesProductsIndexRoute
  '/invoices/quotes/': typeof AuthenticatedInvoicesQuotesIndexRoute
  '/invoices/settings/': typeof AuthenticatedInvoicesSettingsIndexRoute
  '/projects/gantt/': typeof AuthenticatedProjectsGanttIndexRoute
  '/projects/kanban/': typeof AuthenticatedProjectsKanbanIndexRoute
  '/projects/time/': typeof AuthenticatedProjectsTimeIndexRoute
  '/tickets/automations/': typeof AuthenticatedTicketsAutomationsIndexRoute
  '/tickets/inbox/': typeof AuthenticatedTicketsInboxIndexRoute
  '/tickets/knowledge-base/': typeof AuthenticatedTicketsKnowledgeBaseIndexRoute
  '/tickets/settings/': typeof AuthenticatedTicketsSettingsIndexRoute
  '/tickets/stats/': typeof AuthenticatedTicketsStatsIndexRoute
  '/client-portal/project/$projectId/': typeof ClientPortalProjectProjectIdIndexRoute
  '/projects/$projectId/client-portal/': typeof AuthenticatedProjectsProjectIdClientPortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/docs': typeof AuthenticatedDocsRouteWithChildren
  '/client-portal/$token': typeof ClientPortalTokenRoute
  '/client-portal': typeof ClientPortalIndexRoute
  '/analytics/dashboards': typeof AuthenticatedAnalyticsDashboardsRoute
  '/analytics/goals': typeof AuthenticatedAnalyticsGoalsRoute
  '/analytics/reports': typeof AuthenticatedAnalyticsReportsRoute
  '/analytics/settings': typeof AuthenticatedAnalyticsSettingsRoute
  '/docs/activity': typeof AuthenticatedDocsActivityRoute
  '/docs/favorites': typeof AuthenticatedDocsFavoritesRoute
  '/docs/recent': typeof AuthenticatedDocsRecentRoute
  '/docs/settings': typeof AuthenticatedDocsSettingsRoute
  '/docs/trash': typeof AuthenticatedDocsTrashRoute
  '/hr/reports': typeof AuthenticatedHrReportsRoute
  '/hr/settings': typeof AuthenticatedHrSettingsRoute
  '/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/settings/data': typeof AuthenticatedSettingsDataRoute
  '/settings/modules': typeof AuthenticatedSettingsModulesRouteWithChildren
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/settings/preferences': typeof AuthenticatedSettingsPreferencesRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/tickets/$ticketId': typeof AuthenticatedTicketsTicketIdRoute
  '/tickets/new': typeof AuthenticatedTicketsNewRoute
  '/analytics': typeof AuthenticatedAnalyticsIndexRoute
  '/crm': typeof AuthenticatedCrmIndexRoute
  '/hr': typeof AuthenticatedHrIndexRoute
  '/invoices': typeof AuthenticatedInvoicesIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tickets': typeof AuthenticatedTicketsIndexRoute
  '/analytics/dashboard/$dashboardId': typeof AuthenticatedAnalyticsDashboardDashboardIdRoute
  '/crm/companies/$companyId': typeof AuthenticatedCrmCompaniesCompanyIdRoute
  '/crm/companies/new': typeof AuthenticatedCrmCompaniesNewRoute
  '/crm/contacts/$contactId': typeof AuthenticatedCrmContactsContactIdRoute
  '/crm/contacts/new': typeof AuthenticatedCrmContactsNewRoute
  '/docs/file/$fileId': typeof AuthenticatedDocsFileFileIdRoute
  '/docs/folder/$folderId': typeof AuthenticatedDocsFolderFolderIdRoute
  '/hr/employees/$employeeId': typeof AuthenticatedHrEmployeesEmployeeIdRoute
  '/hr/employees/new': typeof AuthenticatedHrEmployeesNewRoute
  '/invoices/clients/$clientId': typeof AuthenticatedInvoicesClientsClientIdRoute
  '/invoices/clients/new': typeof AuthenticatedInvoicesClientsNewRoute
  '/invoices/products/new': typeof AuthenticatedInvoicesProductsNewRoute
  '/invoices/quotes/$quoteId': typeof AuthenticatedInvoicesQuotesQuoteIdRoute
  '/invoices/quotes/new': typeof AuthenticatedInvoicesQuotesNewRoute
  '/settings/modules/compare': typeof AuthenticatedSettingsModulesCompareRoute
  '/crm/activities': typeof AuthenticatedCrmActivitiesIndexRoute
  '/crm/companies': typeof AuthenticatedCrmCompaniesIndexRoute
  '/crm/contacts': typeof AuthenticatedCrmContactsIndexRoute
  '/crm/pipeline': typeof AuthenticatedCrmPipelineIndexRoute
  '/hr/alerts': typeof AuthenticatedHrAlertsIndexRoute
  '/hr/interviews': typeof AuthenticatedHrInterviewsIndexRoute
  '/hr/leaves': typeof AuthenticatedHrLeavesIndexRoute
  '/hr/time-tracking': typeof AuthenticatedHrTimeTrackingIndexRoute
  '/invoices/clients': typeof AuthenticatedInvoicesClientsIndexRoute
  '/invoices/products': typeof AuthenticatedInvoicesProductsIndexRoute
  '/invoices/quotes': typeof AuthenticatedInvoicesQuotesIndexRoute
  '/invoices/settings': typeof AuthenticatedInvoicesSettingsIndexRoute
  '/projects/gantt': typeof AuthenticatedProjectsGanttIndexRoute
  '/projects/kanban': typeof AuthenticatedProjectsKanbanIndexRoute
  '/projects/time': typeof AuthenticatedProjectsTimeIndexRoute
  '/tickets/automations': typeof AuthenticatedTicketsAutomationsIndexRoute
  '/tickets/inbox': typeof AuthenticatedTicketsInboxIndexRoute
  '/tickets/knowledge-base': typeof AuthenticatedTicketsKnowledgeBaseIndexRoute
  '/tickets/settings': typeof AuthenticatedTicketsSettingsIndexRoute
  '/tickets/stats': typeof AuthenticatedTicketsStatsIndexRoute
  '/client-portal/project/$projectId': typeof ClientPortalProjectProjectIdIndexRoute
  '/projects/$projectId/client-portal': typeof AuthenticatedProjectsProjectIdClientPortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRouteWithChildren
  '/_authenticated/crm': typeof AuthenticatedCrmRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/docs': typeof AuthenticatedDocsRouteWithChildren
  '/_authenticated/hr': typeof AuthenticatedHrRouteWithChildren
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRouteWithChildren
  '/_authenticated/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/tickets': typeof AuthenticatedTicketsRouteWithChildren
  '/client-portal/$token': typeof ClientPortalTokenRoute
  '/client-portal/': typeof ClientPortalIndexRoute
  '/_authenticated/analytics/dashboards': typeof AuthenticatedAnalyticsDashboardsRoute
  '/_authenticated/analytics/goals': typeof AuthenticatedAnalyticsGoalsRoute
  '/_authenticated/analytics/reports': typeof AuthenticatedAnalyticsReportsRoute
  '/_authenticated/analytics/settings': typeof AuthenticatedAnalyticsSettingsRoute
  '/_authenticated/docs/activity': typeof AuthenticatedDocsActivityRoute
  '/_authenticated/docs/favorites': typeof AuthenticatedDocsFavoritesRoute
  '/_authenticated/docs/recent': typeof AuthenticatedDocsRecentRoute
  '/_authenticated/docs/settings': typeof AuthenticatedDocsSettingsRoute
  '/_authenticated/docs/trash': typeof AuthenticatedDocsTrashRoute
  '/_authenticated/hr/reports': typeof AuthenticatedHrReportsRoute
  '/_authenticated/hr/settings': typeof AuthenticatedHrSettingsRoute
  '/_authenticated/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/_authenticated/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/_authenticated/projects/new': typeof AuthenticatedProjectsNewRoute
  '/_authenticated/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/_authenticated/settings/data': typeof AuthenticatedSettingsDataRoute
  '/_authenticated/settings/modules': typeof AuthenticatedSettingsModulesRouteWithChildren
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/_authenticated/settings/preferences': typeof AuthenticatedSettingsPreferencesRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/_authenticated/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/_authenticated/tickets/$ticketId': typeof AuthenticatedTicketsTicketIdRoute
  '/_authenticated/tickets/new': typeof AuthenticatedTicketsNewRoute
  '/_authenticated/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/_authenticated/crm/': typeof AuthenticatedCrmIndexRoute
  '/_authenticated/hr/': typeof AuthenticatedHrIndexRoute
  '/_authenticated/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tickets/': typeof AuthenticatedTicketsIndexRoute
  '/_authenticated/analytics/dashboard/$dashboardId': typeof AuthenticatedAnalyticsDashboardDashboardIdRoute
  '/_authenticated/crm/companies/$companyId': typeof AuthenticatedCrmCompaniesCompanyIdRoute
  '/_authenticated/crm/companies/new': typeof AuthenticatedCrmCompaniesNewRoute
  '/_authenticated/crm/contacts/$contactId': typeof AuthenticatedCrmContactsContactIdRoute
  '/_authenticated/crm/contacts/new': typeof AuthenticatedCrmContactsNewRoute
  '/_authenticated/docs/file/$fileId': typeof AuthenticatedDocsFileFileIdRoute
  '/_authenticated/docs/folder/$folderId': typeof AuthenticatedDocsFolderFolderIdRoute
  '/_authenticated/hr/employees/$employeeId': typeof AuthenticatedHrEmployeesEmployeeIdRoute
  '/_authenticated/hr/employees/new': typeof AuthenticatedHrEmployeesNewRoute
  '/_authenticated/invoices/clients/$clientId': typeof AuthenticatedInvoicesClientsClientIdRoute
  '/_authenticated/invoices/clients/new': typeof AuthenticatedInvoicesClientsNewRoute
  '/_authenticated/invoices/products/new': typeof AuthenticatedInvoicesProductsNewRoute
  '/_authenticated/invoices/quotes/$quoteId': typeof AuthenticatedInvoicesQuotesQuoteIdRoute
  '/_authenticated/invoices/quotes/new': typeof AuthenticatedInvoicesQuotesNewRoute
  '/_authenticated/settings/modules/compare': typeof AuthenticatedSettingsModulesCompareRoute
  '/_authenticated/crm/activities/': typeof AuthenticatedCrmActivitiesIndexRoute
  '/_authenticated/crm/companies/': typeof AuthenticatedCrmCompaniesIndexRoute
  '/_authenticated/crm/contacts/': typeof AuthenticatedCrmContactsIndexRoute
  '/_authenticated/crm/pipeline/': typeof AuthenticatedCrmPipelineIndexRoute
  '/_authenticated/hr/alerts/': typeof AuthenticatedHrAlertsIndexRoute
  '/_authenticated/hr/interviews/': typeof AuthenticatedHrInterviewsIndexRoute
  '/_authenticated/hr/leaves/': typeof AuthenticatedHrLeavesIndexRoute
  '/_authenticated/hr/time-tracking/': typeof AuthenticatedHrTimeTrackingIndexRoute
  '/_authenticated/invoices/clients/': typeof AuthenticatedInvoicesClientsIndexRoute
  '/_authenticated/invoices/products/': typeof AuthenticatedInvoicesProductsIndexRoute
  '/_authenticated/invoices/quotes/': typeof AuthenticatedInvoicesQuotesIndexRoute
  '/_authenticated/invoices/settings/': typeof AuthenticatedInvoicesSettingsIndexRoute
  '/_authenticated/projects/gantt/': typeof AuthenticatedProjectsGanttIndexRoute
  '/_authenticated/projects/kanban/': typeof AuthenticatedProjectsKanbanIndexRoute
  '/_authenticated/projects/time/': typeof AuthenticatedProjectsTimeIndexRoute
  '/_authenticated/tickets/automations/': typeof AuthenticatedTicketsAutomationsIndexRoute
  '/_authenticated/tickets/inbox/': typeof AuthenticatedTicketsInboxIndexRoute
  '/_authenticated/tickets/knowledge-base/': typeof AuthenticatedTicketsKnowledgeBaseIndexRoute
  '/_authenticated/tickets/settings/': typeof AuthenticatedTicketsSettingsIndexRoute
  '/_authenticated/tickets/stats/': typeof AuthenticatedTicketsStatsIndexRoute
  '/client-portal/project/$projectId/': typeof ClientPortalProjectProjectIdIndexRoute
  '/_authenticated/projects/$projectId/client-portal/': typeof AuthenticatedProjectsProjectIdClientPortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/setup'
    | '/signup'
    | '/verify-email'
    | '/analytics'
    | '/crm'
    | '/dashboard'
    | '/docs'
    | '/hr'
    | '/invoices'
    | '/projects'
    | '/settings'
    | '/tickets'
    | '/client-portal/$token'
    | '/client-portal/'
    | '/analytics/dashboards'
    | '/analytics/goals'
    | '/analytics/reports'
    | '/analytics/settings'
    | '/docs/activity'
    | '/docs/favorites'
    | '/docs/recent'
    | '/docs/settings'
    | '/docs/trash'
    | '/hr/reports'
    | '/hr/settings'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/projects/$projectId'
    | '/projects/new'
    | '/settings/billing'
    | '/settings/data'
    | '/settings/modules'
    | '/settings/notifications'
    | '/settings/organization'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/team'
    | '/tickets/$ticketId'
    | '/tickets/new'
    | '/analytics/'
    | '/crm/'
    | '/hr/'
    | '/invoices/'
    | '/projects/'
    | '/settings/'
    | '/tickets/'
    | '/analytics/dashboard/$dashboardId'
    | '/crm/companies/$companyId'
    | '/crm/companies/new'
    | '/crm/contacts/$contactId'
    | '/crm/contacts/new'
    | '/docs/file/$fileId'
    | '/docs/folder/$folderId'
    | '/hr/employees/$employeeId'
    | '/hr/employees/new'
    | '/invoices/clients/$clientId'
    | '/invoices/clients/new'
    | '/invoices/products/new'
    | '/invoices/quotes/$quoteId'
    | '/invoices/quotes/new'
    | '/settings/modules/compare'
    | '/crm/activities/'
    | '/crm/companies/'
    | '/crm/contacts/'
    | '/crm/pipeline/'
    | '/hr/alerts/'
    | '/hr/interviews/'
    | '/hr/leaves/'
    | '/hr/time-tracking/'
    | '/invoices/clients/'
    | '/invoices/products/'
    | '/invoices/quotes/'
    | '/invoices/settings/'
    | '/projects/gantt/'
    | '/projects/kanban/'
    | '/projects/time/'
    | '/tickets/automations/'
    | '/tickets/inbox/'
    | '/tickets/knowledge-base/'
    | '/tickets/settings/'
    | '/tickets/stats/'
    | '/client-portal/project/$projectId/'
    | '/projects/$projectId/client-portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/setup'
    | '/signup'
    | '/verify-email'
    | '/dashboard'
    | '/docs'
    | '/client-portal/$token'
    | '/client-portal'
    | '/analytics/dashboards'
    | '/analytics/goals'
    | '/analytics/reports'
    | '/analytics/settings'
    | '/docs/activity'
    | '/docs/favorites'
    | '/docs/recent'
    | '/docs/settings'
    | '/docs/trash'
    | '/hr/reports'
    | '/hr/settings'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/projects/$projectId'
    | '/projects/new'
    | '/settings/billing'
    | '/settings/data'
    | '/settings/modules'
    | '/settings/notifications'
    | '/settings/organization'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/team'
    | '/tickets/$ticketId'
    | '/tickets/new'
    | '/analytics'
    | '/crm'
    | '/hr'
    | '/invoices'
    | '/projects'
    | '/settings'
    | '/tickets'
    | '/analytics/dashboard/$dashboardId'
    | '/crm/companies/$companyId'
    | '/crm/companies/new'
    | '/crm/contacts/$contactId'
    | '/crm/contacts/new'
    | '/docs/file/$fileId'
    | '/docs/folder/$folderId'
    | '/hr/employees/$employeeId'
    | '/hr/employees/new'
    | '/invoices/clients/$clientId'
    | '/invoices/clients/new'
    | '/invoices/products/new'
    | '/invoices/quotes/$quoteId'
    | '/invoices/quotes/new'
    | '/settings/modules/compare'
    | '/crm/activities'
    | '/crm/companies'
    | '/crm/contacts'
    | '/crm/pipeline'
    | '/hr/alerts'
    | '/hr/interviews'
    | '/hr/leaves'
    | '/hr/time-tracking'
    | '/invoices/clients'
    | '/invoices/products'
    | '/invoices/quotes'
    | '/invoices/settings'
    | '/projects/gantt'
    | '/projects/kanban'
    | '/projects/time'
    | '/tickets/automations'
    | '/tickets/inbox'
    | '/tickets/knowledge-base'
    | '/tickets/settings'
    | '/tickets/stats'
    | '/client-portal/project/$projectId'
    | '/projects/$projectId/client-portal'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/setup'
    | '/signup'
    | '/verify-email'
    | '/_authenticated/analytics'
    | '/_authenticated/crm'
    | '/_authenticated/dashboard'
    | '/_authenticated/docs'
    | '/_authenticated/hr'
    | '/_authenticated/invoices'
    | '/_authenticated/projects'
    | '/_authenticated/settings'
    | '/_authenticated/tickets'
    | '/client-portal/$token'
    | '/client-portal/'
    | '/_authenticated/analytics/dashboards'
    | '/_authenticated/analytics/goals'
    | '/_authenticated/analytics/reports'
    | '/_authenticated/analytics/settings'
    | '/_authenticated/docs/activity'
    | '/_authenticated/docs/favorites'
    | '/_authenticated/docs/recent'
    | '/_authenticated/docs/settings'
    | '/_authenticated/docs/trash'
    | '/_authenticated/hr/reports'
    | '/_authenticated/hr/settings'
    | '/_authenticated/invoices/$invoiceId'
    | '/_authenticated/invoices/new'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/projects/new'
    | '/_authenticated/settings/billing'
    | '/_authenticated/settings/data'
    | '/_authenticated/settings/modules'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/organization'
    | '/_authenticated/settings/preferences'
    | '/_authenticated/settings/profile'
    | '/_authenticated/settings/security'
    | '/_authenticated/settings/team'
    | '/_authenticated/tickets/$ticketId'
    | '/_authenticated/tickets/new'
    | '/_authenticated/analytics/'
    | '/_authenticated/crm/'
    | '/_authenticated/hr/'
    | '/_authenticated/invoices/'
    | '/_authenticated/projects/'
    | '/_authenticated/settings/'
    | '/_authenticated/tickets/'
    | '/_authenticated/analytics/dashboard/$dashboardId'
    | '/_authenticated/crm/companies/$companyId'
    | '/_authenticated/crm/companies/new'
    | '/_authenticated/crm/contacts/$contactId'
    | '/_authenticated/crm/contacts/new'
    | '/_authenticated/docs/file/$fileId'
    | '/_authenticated/docs/folder/$folderId'
    | '/_authenticated/hr/employees/$employeeId'
    | '/_authenticated/hr/employees/new'
    | '/_authenticated/invoices/clients/$clientId'
    | '/_authenticated/invoices/clients/new'
    | '/_authenticated/invoices/products/new'
    | '/_authenticated/invoices/quotes/$quoteId'
    | '/_authenticated/invoices/quotes/new'
    | '/_authenticated/settings/modules/compare'
    | '/_authenticated/crm/activities/'
    | '/_authenticated/crm/companies/'
    | '/_authenticated/crm/contacts/'
    | '/_authenticated/crm/pipeline/'
    | '/_authenticated/hr/alerts/'
    | '/_authenticated/hr/interviews/'
    | '/_authenticated/hr/leaves/'
    | '/_authenticated/hr/time-tracking/'
    | '/_authenticated/invoices/clients/'
    | '/_authenticated/invoices/products/'
    | '/_authenticated/invoices/quotes/'
    | '/_authenticated/invoices/settings/'
    | '/_authenticated/projects/gantt/'
    | '/_authenticated/projects/kanban/'
    | '/_authenticated/projects/time/'
    | '/_authenticated/tickets/automations/'
    | '/_authenticated/tickets/inbox/'
    | '/_authenticated/tickets/knowledge-base/'
    | '/_authenticated/tickets/settings/'
    | '/_authenticated/tickets/stats/'
    | '/client-portal/project/$projectId/'
    | '/_authenticated/projects/$projectId/client-portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ClientPortalTokenRoute: typeof ClientPortalTokenRoute
  ClientPortalIndexRoute: typeof ClientPortalIndexRoute
  ClientPortalProjectProjectIdIndexRoute: typeof ClientPortalProjectProjectIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-portal/': {
      id: '/client-portal/'
      path: '/client-portal'
      fullPath: '/client-portal/'
      preLoaderRoute: typeof ClientPortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-portal/$token': {
      id: '/client-portal/$token'
      path: '/client-portal/$token'
      fullPath: '/client-portal/$token'
      preLoaderRoute: typeof ClientPortalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tickets': {
      id: '/_authenticated/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr': {
      id: '/_authenticated/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AuthenticatedHrRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/docs': {
      id: '/_authenticated/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AuthenticatedDocsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tickets/': {
      id: '/_authenticated/tickets/'
      path: '/'
      fullPath: '/tickets/'
      preLoaderRoute: typeof AuthenticatedTicketsIndexRouteImport
      parentRoute: typeof AuthenticatedTicketsRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/invoices/': {
      id: '/_authenticated/invoices/'
      path: '/'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthenticatedInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedInvoicesRoute
    }
    '/_authenticated/hr/': {
      id: '/_authenticated/hr/'
      path: '/'
      fullPath: '/hr/'
      preLoaderRoute: typeof AuthenticatedHrIndexRouteImport
      parentRoute: typeof AuthenticatedHrRoute
    }
    '/_authenticated/crm/': {
      id: '/_authenticated/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof AuthenticatedCrmIndexRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/analytics/': {
      id: '/_authenticated/analytics/'
      path: '/'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AuthenticatedAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedAnalyticsRoute
    }
    '/_authenticated/tickets/new': {
      id: '/_authenticated/tickets/new'
      path: '/new'
      fullPath: '/tickets/new'
      preLoaderRoute: typeof AuthenticatedTicketsNewRouteImport
      parentRoute: typeof AuthenticatedTicketsRoute
    }
    '/_authenticated/tickets/$ticketId': {
      id: '/_authenticated/tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof AuthenticatedTicketsTicketIdRouteImport
      parentRoute: typeof AuthenticatedTicketsRoute
    }
    '/_authenticated/settings/team': {
      id: '/_authenticated/settings/team'
      path: '/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof AuthenticatedSettingsTeamRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/security': {
      id: '/_authenticated/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/preferences': {
      id: '/_authenticated/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof AuthenticatedSettingsPreferencesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/organization': {
      id: '/_authenticated/settings/organization'
      path: '/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof AuthenticatedSettingsOrganizationRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/modules': {
      id: '/_authenticated/settings/modules'
      path: '/modules'
      fullPath: '/settings/modules'
      preLoaderRoute: typeof AuthenticatedSettingsModulesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/data': {
      id: '/_authenticated/settings/data'
      path: '/data'
      fullPath: '/settings/data'
      preLoaderRoute: typeof AuthenticatedSettingsDataRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/billing': {
      id: '/_authenticated/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AuthenticatedSettingsBillingRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/projects/new': {
      id: '/_authenticated/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AuthenticatedProjectsNewRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/invoices/new': {
      id: '/_authenticated/invoices/new'
      path: '/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AuthenticatedInvoicesNewRouteImport
      parentRoute: typeof AuthenticatedInvoicesRoute
    }
    '/_authenticated/invoices/$invoiceId': {
      id: '/_authenticated/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof AuthenticatedInvoicesInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedInvoicesRoute
    }
    '/_authenticated/hr/settings': {
      id: '/_authenticated/hr/settings'
      path: '/settings'
      fullPath: '/hr/settings'
      preLoaderRoute: typeof AuthenticatedHrSettingsRouteImport
      parentRoute: typeof AuthenticatedHrRoute
    }
    '/_authenticated/hr/reports': {
      id: '/_authenticated/hr/reports'
      path: '/reports'
      fullPath: '/hr/reports'
      preLoaderRoute: typeof AuthenticatedHrReportsRouteImport
      parentRoute: typeof AuthenticatedHrRoute
    }
    '/_authenticated/docs/trash': {
      id: '/_authenticated/docs/trash'
      path: '/trash'
      fullPath: '/docs/trash'
      preLoaderRoute: typeof AuthenticatedDocsTrashRouteImport
      parentRoute: typeof AuthenticatedDocsRoute
    }
    '/_authenticated/docs/settings': {
      id: '/_authenticated/docs/settings'
      path: '/settings'
      fullPath: '/docs/settings'
      preLoaderRoute: typeof AuthenticatedDocsSettingsRouteImport
      parentRoute: typeof AuthenticatedDocsRoute
    }
    '/_authenticated/docs/recent': {
      id: '/_authenticated/docs/recent'
      path: '/recent'
      fullPath: '/docs/recent'
      preLoaderRoute: typeof AuthenticatedDocsRecentRouteImport
      parentRoute: typeof AuthenticatedDocsRoute
    }
    '/_authenticated/docs/favorites': {
      id: '/_authenticated/docs/favorites'
      path: '/favorites'
      fullPath: '/docs/favorites'
      preLoaderRoute: typeof AuthenticatedDocsFavoritesRouteImport
      parentRoute: typeof AuthenticatedDocsRoute
    }
    '/_authenticated/docs/activity': {
      id: '/_authenticated/docs/activity'
      path: '/activity'
      fullPath: '/docs/activity'
      preLoaderRoute: typeof AuthenticatedDocsActivityRouteImport
      parentRoute: typeof AuthenticatedDocsRoute
    }
    '/_authenticated/analytics/settings': {
      id: '/_authenticated/analytics/settings'
      path: '/settings'
      fullPath: '/analytics/settings'
      preLoaderRoute: typeof AuthenticatedAnalyticsSettingsRouteImport
      parentRoute: typeof AuthenticatedAnalyticsRoute
    }
    '/_authenticated/analytics/reports': {
      id: '/_authenticated/analytics/reports'
      path: '/reports'
      fullPath: '/analytics/reports'
      preLoaderRoute: typeof AuthenticatedAnalyticsReportsRouteImport
      parentRoute: typeof AuthenticatedAnalyticsRoute
    }
    '/_authenticated/analytics/goals': {
      id: '/_authenticated/analytics/goals'
      path: '/goals'
      fullPath: '/analytics/goals'
      preLoaderRoute: typeof AuthenticatedAnalyticsGoalsRouteImport
      parentRoute: typeof AuthenticatedAnalyticsRoute
    }
    '/_authenticated/analytics/dashboards': {
      id: '/_authenticated/analytics/dashboards'
      path: '/dashboards'
      fullPath: '/analytics/dashboards'
      preLoaderRoute: typeof AuthenticatedAnalyticsDashboardsRouteImport
      parentRoute: typeof AuthenticatedAnalyticsRoute
    }
    '/client-portal/project/$projectId/': {
      id: '/client-portal/project/$projectId/'
      path: '/client-portal/project/$projectId'
      fullPath: '/client-portal/project/$projectId/'
      preLoaderRoute: typeof ClientPortalProjectProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tickets/stats/': {
      id: '/_authenticated/tickets/stats/'
      path: '/stats'
      fullPath: '/tickets/stats/'
      preLoaderRoute: typeof AuthenticatedTicketsStatsIndexRouteImport
      parentRoute: typeof AuthenticatedTicketsRoute
    }
    '/_authenticated/tickets/settings/': {
      id: '/_authenticated/tickets/settings/'
      path: '/settings'
      fullPath: '/tickets/settings/'
      preLoaderRoute: typeof AuthenticatedTicketsSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedTicketsRoute
    }
    '/_authenticated/tickets/knowledge-base/': {
      id: '/_authenticated/tickets/knowledge-base/'
      path: '/knowledge-base'
      fullPath: '/tickets/knowledge-base/'
      preLoaderRoute: typeof AuthenticatedTicketsKnowledgeBaseIndexRouteImport
      parentRoute: typeof AuthenticatedTicketsRoute
    }
    '/_authenticated/tickets/inbox/': {
      id: '/_authenticated/tickets/inbox/'
      path: '/inbox'
      fullPath: '/tickets/inbox/'
      preLoaderRoute: typeof AuthenticatedTicketsInboxIndexRouteImport
      parentRoute: typeof AuthenticatedTicketsRoute
    }
    '/_authenticated/tickets/automations/': {
      id: '/_authenticated/tickets/automations/'
      path: '/automations'
      fullPath: '/tickets/automations/'
      preLoaderRoute: typeof AuthenticatedTicketsAutomationsIndexRouteImport
      parentRoute: typeof AuthenticatedTicketsRoute
    }
    '/_authenticated/projects/time/': {
      id: '/_authenticated/projects/time/'
      path: '/time'
      fullPath: '/projects/time/'
      preLoaderRoute: typeof AuthenticatedProjectsTimeIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/projects/kanban/': {
      id: '/_authenticated/projects/kanban/'
      path: '/kanban'
      fullPath: '/projects/kanban/'
      preLoaderRoute: typeof AuthenticatedProjectsKanbanIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/projects/gantt/': {
      id: '/_authenticated/projects/gantt/'
      path: '/gantt'
      fullPath: '/projects/gantt/'
      preLoaderRoute: typeof AuthenticatedProjectsGanttIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/invoices/settings/': {
      id: '/_authenticated/invoices/settings/'
      path: '/settings'
      fullPath: '/invoices/settings/'
      preLoaderRoute: typeof AuthenticatedInvoicesSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedInvoicesRoute
    }
    '/_authenticated/invoices/quotes/': {
      id: '/_authenticated/invoices/quotes/'
      path: '/quotes'
      fullPath: '/invoices/quotes/'
      preLoaderRoute: typeof AuthenticatedInvoicesQuotesIndexRouteImport
      parentRoute: typeof AuthenticatedInvoicesRoute
    }
    '/_authenticated/invoices/products/': {
      id: '/_authenticated/invoices/products/'
      path: '/products'
      fullPath: '/invoices/products/'
      preLoaderRoute: typeof AuthenticatedInvoicesProductsIndexRouteImport
      parentRoute: typeof AuthenticatedInvoicesRoute
    }
    '/_authenticated/invoices/clients/': {
      id: '/_authenticated/invoices/clients/'
      path: '/clients'
      fullPath: '/invoices/clients/'
      preLoaderRoute: typeof AuthenticatedInvoicesClientsIndexRouteImport
      parentRoute: typeof AuthenticatedInvoicesRoute
    }
    '/_authenticated/hr/time-tracking/': {
      id: '/_authenticated/hr/time-tracking/'
      path: '/time-tracking'
      fullPath: '/hr/time-tracking/'
      preLoaderRoute: typeof AuthenticatedHrTimeTrackingIndexRouteImport
      parentRoute: typeof AuthenticatedHrRoute
    }
    '/_authenticated/hr/leaves/': {
      id: '/_authenticated/hr/leaves/'
      path: '/leaves'
      fullPath: '/hr/leaves/'
      preLoaderRoute: typeof AuthenticatedHrLeavesIndexRouteImport
      parentRoute: typeof AuthenticatedHrRoute
    }
    '/_authenticated/hr/interviews/': {
      id: '/_authenticated/hr/interviews/'
      path: '/interviews'
      fullPath: '/hr/interviews/'
      preLoaderRoute: typeof AuthenticatedHrInterviewsIndexRouteImport
      parentRoute: typeof AuthenticatedHrRoute
    }
    '/_authenticated/hr/alerts/': {
      id: '/_authenticated/hr/alerts/'
      path: '/alerts'
      fullPath: '/hr/alerts/'
      preLoaderRoute: typeof AuthenticatedHrAlertsIndexRouteImport
      parentRoute: typeof AuthenticatedHrRoute
    }
    '/_authenticated/crm/pipeline/': {
      id: '/_authenticated/crm/pipeline/'
      path: '/pipeline'
      fullPath: '/crm/pipeline/'
      preLoaderRoute: typeof AuthenticatedCrmPipelineIndexRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/contacts/': {
      id: '/_authenticated/crm/contacts/'
      path: '/contacts'
      fullPath: '/crm/contacts/'
      preLoaderRoute: typeof AuthenticatedCrmContactsIndexRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/companies/': {
      id: '/_authenticated/crm/companies/'
      path: '/companies'
      fullPath: '/crm/companies/'
      preLoaderRoute: typeof AuthenticatedCrmCompaniesIndexRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/activities/': {
      id: '/_authenticated/crm/activities/'
      path: '/activities'
      fullPath: '/crm/activities/'
      preLoaderRoute: typeof AuthenticatedCrmActivitiesIndexRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/settings/modules/compare': {
      id: '/_authenticated/settings/modules/compare'
      path: '/compare'
      fullPath: '/settings/modules/compare'
      preLoaderRoute: typeof AuthenticatedSettingsModulesCompareRouteImport
      parentRoute: typeof AuthenticatedSettingsModulesRoute
    }
    '/_authenticated/invoices/quotes/new': {
      id: '/_authenticated/invoices/quotes/new'
      path: '/quotes/new'
      fullPath: '/invoices/quotes/new'
      preLoaderRoute: typeof AuthenticatedInvoicesQuotesNewRouteImport
      parentRoute: typeof AuthenticatedInvoicesRoute
    }
    '/_authenticated/invoices/quotes/$quoteId': {
      id: '/_authenticated/invoices/quotes/$quoteId'
      path: '/quotes/$quoteId'
      fullPath: '/invoices/quotes/$quoteId'
      preLoaderRoute: typeof AuthenticatedInvoicesQuotesQuoteIdRouteImport
      parentRoute: typeof AuthenticatedInvoicesRoute
    }
    '/_authenticated/invoices/products/new': {
      id: '/_authenticated/invoices/products/new'
      path: '/products/new'
      fullPath: '/invoices/products/new'
      preLoaderRoute: typeof AuthenticatedInvoicesProductsNewRouteImport
      parentRoute: typeof AuthenticatedInvoicesRoute
    }
    '/_authenticated/invoices/clients/new': {
      id: '/_authenticated/invoices/clients/new'
      path: '/clients/new'
      fullPath: '/invoices/clients/new'
      preLoaderRoute: typeof AuthenticatedInvoicesClientsNewRouteImport
      parentRoute: typeof AuthenticatedInvoicesRoute
    }
    '/_authenticated/invoices/clients/$clientId': {
      id: '/_authenticated/invoices/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/invoices/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedInvoicesClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedInvoicesRoute
    }
    '/_authenticated/hr/employees/new': {
      id: '/_authenticated/hr/employees/new'
      path: '/employees/new'
      fullPath: '/hr/employees/new'
      preLoaderRoute: typeof AuthenticatedHrEmployeesNewRouteImport
      parentRoute: typeof AuthenticatedHrRoute
    }
    '/_authenticated/hr/employees/$employeeId': {
      id: '/_authenticated/hr/employees/$employeeId'
      path: '/employees/$employeeId'
      fullPath: '/hr/employees/$employeeId'
      preLoaderRoute: typeof AuthenticatedHrEmployeesEmployeeIdRouteImport
      parentRoute: typeof AuthenticatedHrRoute
    }
    '/_authenticated/docs/folder/$folderId': {
      id: '/_authenticated/docs/folder/$folderId'
      path: '/folder/$folderId'
      fullPath: '/docs/folder/$folderId'
      preLoaderRoute: typeof AuthenticatedDocsFolderFolderIdRouteImport
      parentRoute: typeof AuthenticatedDocsRoute
    }
    '/_authenticated/docs/file/$fileId': {
      id: '/_authenticated/docs/file/$fileId'
      path: '/file/$fileId'
      fullPath: '/docs/file/$fileId'
      preLoaderRoute: typeof AuthenticatedDocsFileFileIdRouteImport
      parentRoute: typeof AuthenticatedDocsRoute
    }
    '/_authenticated/crm/contacts/new': {
      id: '/_authenticated/crm/contacts/new'
      path: '/contacts/new'
      fullPath: '/crm/contacts/new'
      preLoaderRoute: typeof AuthenticatedCrmContactsNewRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/contacts/$contactId': {
      id: '/_authenticated/crm/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/crm/contacts/$contactId'
      preLoaderRoute: typeof AuthenticatedCrmContactsContactIdRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/companies/new': {
      id: '/_authenticated/crm/companies/new'
      path: '/companies/new'
      fullPath: '/crm/companies/new'
      preLoaderRoute: typeof AuthenticatedCrmCompaniesNewRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/companies/$companyId': {
      id: '/_authenticated/crm/companies/$companyId'
      path: '/companies/$companyId'
      fullPath: '/crm/companies/$companyId'
      preLoaderRoute: typeof AuthenticatedCrmCompaniesCompanyIdRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/analytics/dashboard/$dashboardId': {
      id: '/_authenticated/analytics/dashboard/$dashboardId'
      path: '/dashboard/$dashboardId'
      fullPath: '/analytics/dashboard/$dashboardId'
      preLoaderRoute: typeof AuthenticatedAnalyticsDashboardDashboardIdRouteImport
      parentRoute: typeof AuthenticatedAnalyticsRoute
    }
    '/_authenticated/projects/$projectId/client-portal/': {
      id: '/_authenticated/projects/$projectId/client-portal/'
      path: '/client-portal'
      fullPath: '/projects/$projectId/client-portal/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdClientPortalIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
  }
}

interface AuthenticatedAnalyticsRouteChildren {
  AuthenticatedAnalyticsDashboardsRoute: typeof AuthenticatedAnalyticsDashboardsRoute
  AuthenticatedAnalyticsGoalsRoute: typeof AuthenticatedAnalyticsGoalsRoute
  AuthenticatedAnalyticsReportsRoute: typeof AuthenticatedAnalyticsReportsRoute
  AuthenticatedAnalyticsSettingsRoute: typeof AuthenticatedAnalyticsSettingsRoute
  AuthenticatedAnalyticsIndexRoute: typeof AuthenticatedAnalyticsIndexRoute
  AuthenticatedAnalyticsDashboardDashboardIdRoute: typeof AuthenticatedAnalyticsDashboardDashboardIdRoute
}

const AuthenticatedAnalyticsRouteChildren: AuthenticatedAnalyticsRouteChildren =
  {
    AuthenticatedAnalyticsDashboardsRoute:
      AuthenticatedAnalyticsDashboardsRoute,
    AuthenticatedAnalyticsGoalsRoute: AuthenticatedAnalyticsGoalsRoute,
    AuthenticatedAnalyticsReportsRoute: AuthenticatedAnalyticsReportsRoute,
    AuthenticatedAnalyticsSettingsRoute: AuthenticatedAnalyticsSettingsRoute,
    AuthenticatedAnalyticsIndexRoute: AuthenticatedAnalyticsIndexRoute,
    AuthenticatedAnalyticsDashboardDashboardIdRoute:
      AuthenticatedAnalyticsDashboardDashboardIdRoute,
  }

const AuthenticatedAnalyticsRouteWithChildren =
  AuthenticatedAnalyticsRoute._addFileChildren(
    AuthenticatedAnalyticsRouteChildren,
  )

interface AuthenticatedCrmRouteChildren {
  AuthenticatedCrmIndexRoute: typeof AuthenticatedCrmIndexRoute
  AuthenticatedCrmCompaniesCompanyIdRoute: typeof AuthenticatedCrmCompaniesCompanyIdRoute
  AuthenticatedCrmCompaniesNewRoute: typeof AuthenticatedCrmCompaniesNewRoute
  AuthenticatedCrmContactsContactIdRoute: typeof AuthenticatedCrmContactsContactIdRoute
  AuthenticatedCrmContactsNewRoute: typeof AuthenticatedCrmContactsNewRoute
  AuthenticatedCrmActivitiesIndexRoute: typeof AuthenticatedCrmActivitiesIndexRoute
  AuthenticatedCrmCompaniesIndexRoute: typeof AuthenticatedCrmCompaniesIndexRoute
  AuthenticatedCrmContactsIndexRoute: typeof AuthenticatedCrmContactsIndexRoute
  AuthenticatedCrmPipelineIndexRoute: typeof AuthenticatedCrmPipelineIndexRoute
}

const AuthenticatedCrmRouteChildren: AuthenticatedCrmRouteChildren = {
  AuthenticatedCrmIndexRoute: AuthenticatedCrmIndexRoute,
  AuthenticatedCrmCompaniesCompanyIdRoute:
    AuthenticatedCrmCompaniesCompanyIdRoute,
  AuthenticatedCrmCompaniesNewRoute: AuthenticatedCrmCompaniesNewRoute,
  AuthenticatedCrmContactsContactIdRoute:
    AuthenticatedCrmContactsContactIdRoute,
  AuthenticatedCrmContactsNewRoute: AuthenticatedCrmContactsNewRoute,
  AuthenticatedCrmActivitiesIndexRoute: AuthenticatedCrmActivitiesIndexRoute,
  AuthenticatedCrmCompaniesIndexRoute: AuthenticatedCrmCompaniesIndexRoute,
  AuthenticatedCrmContactsIndexRoute: AuthenticatedCrmContactsIndexRoute,
  AuthenticatedCrmPipelineIndexRoute: AuthenticatedCrmPipelineIndexRoute,
}

const AuthenticatedCrmRouteWithChildren =
  AuthenticatedCrmRoute._addFileChildren(AuthenticatedCrmRouteChildren)

interface AuthenticatedDocsRouteChildren {
  AuthenticatedDocsActivityRoute: typeof AuthenticatedDocsActivityRoute
  AuthenticatedDocsFavoritesRoute: typeof AuthenticatedDocsFavoritesRoute
  AuthenticatedDocsRecentRoute: typeof AuthenticatedDocsRecentRoute
  AuthenticatedDocsSettingsRoute: typeof AuthenticatedDocsSettingsRoute
  AuthenticatedDocsTrashRoute: typeof AuthenticatedDocsTrashRoute
  AuthenticatedDocsFileFileIdRoute: typeof AuthenticatedDocsFileFileIdRoute
  AuthenticatedDocsFolderFolderIdRoute: typeof AuthenticatedDocsFolderFolderIdRoute
}

const AuthenticatedDocsRouteChildren: AuthenticatedDocsRouteChildren = {
  AuthenticatedDocsActivityRoute: AuthenticatedDocsActivityRoute,
  AuthenticatedDocsFavoritesRoute: AuthenticatedDocsFavoritesRoute,
  AuthenticatedDocsRecentRoute: AuthenticatedDocsRecentRoute,
  AuthenticatedDocsSettingsRoute: AuthenticatedDocsSettingsRoute,
  AuthenticatedDocsTrashRoute: AuthenticatedDocsTrashRoute,
  AuthenticatedDocsFileFileIdRoute: AuthenticatedDocsFileFileIdRoute,
  AuthenticatedDocsFolderFolderIdRoute: AuthenticatedDocsFolderFolderIdRoute,
}

const AuthenticatedDocsRouteWithChildren =
  AuthenticatedDocsRoute._addFileChildren(AuthenticatedDocsRouteChildren)

interface AuthenticatedHrRouteChildren {
  AuthenticatedHrReportsRoute: typeof AuthenticatedHrReportsRoute
  AuthenticatedHrSettingsRoute: typeof AuthenticatedHrSettingsRoute
  AuthenticatedHrIndexRoute: typeof AuthenticatedHrIndexRoute
  AuthenticatedHrEmployeesEmployeeIdRoute: typeof AuthenticatedHrEmployeesEmployeeIdRoute
  AuthenticatedHrEmployeesNewRoute: typeof AuthenticatedHrEmployeesNewRoute
  AuthenticatedHrAlertsIndexRoute: typeof AuthenticatedHrAlertsIndexRoute
  AuthenticatedHrInterviewsIndexRoute: typeof AuthenticatedHrInterviewsIndexRoute
  AuthenticatedHrLeavesIndexRoute: typeof AuthenticatedHrLeavesIndexRoute
  AuthenticatedHrTimeTrackingIndexRoute: typeof AuthenticatedHrTimeTrackingIndexRoute
}

const AuthenticatedHrRouteChildren: AuthenticatedHrRouteChildren = {
  AuthenticatedHrReportsRoute: AuthenticatedHrReportsRoute,
  AuthenticatedHrSettingsRoute: AuthenticatedHrSettingsRoute,
  AuthenticatedHrIndexRoute: AuthenticatedHrIndexRoute,
  AuthenticatedHrEmployeesEmployeeIdRoute:
    AuthenticatedHrEmployeesEmployeeIdRoute,
  AuthenticatedHrEmployeesNewRoute: AuthenticatedHrEmployeesNewRoute,
  AuthenticatedHrAlertsIndexRoute: AuthenticatedHrAlertsIndexRoute,
  AuthenticatedHrInterviewsIndexRoute: AuthenticatedHrInterviewsIndexRoute,
  AuthenticatedHrLeavesIndexRoute: AuthenticatedHrLeavesIndexRoute,
  AuthenticatedHrTimeTrackingIndexRoute: AuthenticatedHrTimeTrackingIndexRoute,
}

const AuthenticatedHrRouteWithChildren = AuthenticatedHrRoute._addFileChildren(
  AuthenticatedHrRouteChildren,
)

interface AuthenticatedInvoicesRouteChildren {
  AuthenticatedInvoicesInvoiceIdRoute: typeof AuthenticatedInvoicesInvoiceIdRoute
  AuthenticatedInvoicesNewRoute: typeof AuthenticatedInvoicesNewRoute
  AuthenticatedInvoicesIndexRoute: typeof AuthenticatedInvoicesIndexRoute
  AuthenticatedInvoicesClientsClientIdRoute: typeof AuthenticatedInvoicesClientsClientIdRoute
  AuthenticatedInvoicesClientsNewRoute: typeof AuthenticatedInvoicesClientsNewRoute
  AuthenticatedInvoicesProductsNewRoute: typeof AuthenticatedInvoicesProductsNewRoute
  AuthenticatedInvoicesQuotesQuoteIdRoute: typeof AuthenticatedInvoicesQuotesQuoteIdRoute
  AuthenticatedInvoicesQuotesNewRoute: typeof AuthenticatedInvoicesQuotesNewRoute
  AuthenticatedInvoicesClientsIndexRoute: typeof AuthenticatedInvoicesClientsIndexRoute
  AuthenticatedInvoicesProductsIndexRoute: typeof AuthenticatedInvoicesProductsIndexRoute
  AuthenticatedInvoicesQuotesIndexRoute: typeof AuthenticatedInvoicesQuotesIndexRoute
  AuthenticatedInvoicesSettingsIndexRoute: typeof AuthenticatedInvoicesSettingsIndexRoute
}

const AuthenticatedInvoicesRouteChildren: AuthenticatedInvoicesRouteChildren = {
  AuthenticatedInvoicesInvoiceIdRoute: AuthenticatedInvoicesInvoiceIdRoute,
  AuthenticatedInvoicesNewRoute: AuthenticatedInvoicesNewRoute,
  AuthenticatedInvoicesIndexRoute: AuthenticatedInvoicesIndexRoute,
  AuthenticatedInvoicesClientsClientIdRoute:
    AuthenticatedInvoicesClientsClientIdRoute,
  AuthenticatedInvoicesClientsNewRoute: AuthenticatedInvoicesClientsNewRoute,
  AuthenticatedInvoicesProductsNewRoute: AuthenticatedInvoicesProductsNewRoute,
  AuthenticatedInvoicesQuotesQuoteIdRoute:
    AuthenticatedInvoicesQuotesQuoteIdRoute,
  AuthenticatedInvoicesQuotesNewRoute: AuthenticatedInvoicesQuotesNewRoute,
  AuthenticatedInvoicesClientsIndexRoute:
    AuthenticatedInvoicesClientsIndexRoute,
  AuthenticatedInvoicesProductsIndexRoute:
    AuthenticatedInvoicesProductsIndexRoute,
  AuthenticatedInvoicesQuotesIndexRoute: AuthenticatedInvoicesQuotesIndexRoute,
  AuthenticatedInvoicesSettingsIndexRoute:
    AuthenticatedInvoicesSettingsIndexRoute,
}

const AuthenticatedInvoicesRouteWithChildren =
  AuthenticatedInvoicesRoute._addFileChildren(
    AuthenticatedInvoicesRouteChildren,
  )

interface AuthenticatedProjectsProjectIdRouteChildren {
  AuthenticatedProjectsProjectIdClientPortalIndexRoute: typeof AuthenticatedProjectsProjectIdClientPortalIndexRoute
}

const AuthenticatedProjectsProjectIdRouteChildren: AuthenticatedProjectsProjectIdRouteChildren =
  {
    AuthenticatedProjectsProjectIdClientPortalIndexRoute:
      AuthenticatedProjectsProjectIdClientPortalIndexRoute,
  }

const AuthenticatedProjectsProjectIdRouteWithChildren =
  AuthenticatedProjectsProjectIdRoute._addFileChildren(
    AuthenticatedProjectsProjectIdRouteChildren,
  )

interface AuthenticatedProjectsRouteChildren {
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRouteWithChildren
  AuthenticatedProjectsNewRoute: typeof AuthenticatedProjectsNewRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedProjectsGanttIndexRoute: typeof AuthenticatedProjectsGanttIndexRoute
  AuthenticatedProjectsKanbanIndexRoute: typeof AuthenticatedProjectsKanbanIndexRoute
  AuthenticatedProjectsTimeIndexRoute: typeof AuthenticatedProjectsTimeIndexRoute
}

const AuthenticatedProjectsRouteChildren: AuthenticatedProjectsRouteChildren = {
  AuthenticatedProjectsProjectIdRoute:
    AuthenticatedProjectsProjectIdRouteWithChildren,
  AuthenticatedProjectsNewRoute: AuthenticatedProjectsNewRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedProjectsGanttIndexRoute: AuthenticatedProjectsGanttIndexRoute,
  AuthenticatedProjectsKanbanIndexRoute: AuthenticatedProjectsKanbanIndexRoute,
  AuthenticatedProjectsTimeIndexRoute: AuthenticatedProjectsTimeIndexRoute,
}

const AuthenticatedProjectsRouteWithChildren =
  AuthenticatedProjectsRoute._addFileChildren(
    AuthenticatedProjectsRouteChildren,
  )

interface AuthenticatedSettingsModulesRouteChildren {
  AuthenticatedSettingsModulesCompareRoute: typeof AuthenticatedSettingsModulesCompareRoute
}

const AuthenticatedSettingsModulesRouteChildren: AuthenticatedSettingsModulesRouteChildren =
  {
    AuthenticatedSettingsModulesCompareRoute:
      AuthenticatedSettingsModulesCompareRoute,
  }

const AuthenticatedSettingsModulesRouteWithChildren =
  AuthenticatedSettingsModulesRoute._addFileChildren(
    AuthenticatedSettingsModulesRouteChildren,
  )

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsBillingRoute: typeof AuthenticatedSettingsBillingRoute
  AuthenticatedSettingsDataRoute: typeof AuthenticatedSettingsDataRoute
  AuthenticatedSettingsModulesRoute: typeof AuthenticatedSettingsModulesRouteWithChildren
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsOrganizationRoute: typeof AuthenticatedSettingsOrganizationRoute
  AuthenticatedSettingsPreferencesRoute: typeof AuthenticatedSettingsPreferencesRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSettingsSecurityRoute: typeof AuthenticatedSettingsSecurityRoute
  AuthenticatedSettingsTeamRoute: typeof AuthenticatedSettingsTeamRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsBillingRoute: AuthenticatedSettingsBillingRoute,
  AuthenticatedSettingsDataRoute: AuthenticatedSettingsDataRoute,
  AuthenticatedSettingsModulesRoute:
    AuthenticatedSettingsModulesRouteWithChildren,
  AuthenticatedSettingsNotificationsRoute:
    AuthenticatedSettingsNotificationsRoute,
  AuthenticatedSettingsOrganizationRoute:
    AuthenticatedSettingsOrganizationRoute,
  AuthenticatedSettingsPreferencesRoute: AuthenticatedSettingsPreferencesRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedSettingsSecurityRoute: AuthenticatedSettingsSecurityRoute,
  AuthenticatedSettingsTeamRoute: AuthenticatedSettingsTeamRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedTicketsRouteChildren {
  AuthenticatedTicketsTicketIdRoute: typeof AuthenticatedTicketsTicketIdRoute
  AuthenticatedTicketsNewRoute: typeof AuthenticatedTicketsNewRoute
  AuthenticatedTicketsIndexRoute: typeof AuthenticatedTicketsIndexRoute
  AuthenticatedTicketsAutomationsIndexRoute: typeof AuthenticatedTicketsAutomationsIndexRoute
  AuthenticatedTicketsInboxIndexRoute: typeof AuthenticatedTicketsInboxIndexRoute
  AuthenticatedTicketsKnowledgeBaseIndexRoute: typeof AuthenticatedTicketsKnowledgeBaseIndexRoute
  AuthenticatedTicketsSettingsIndexRoute: typeof AuthenticatedTicketsSettingsIndexRoute
  AuthenticatedTicketsStatsIndexRoute: typeof AuthenticatedTicketsStatsIndexRoute
}

const AuthenticatedTicketsRouteChildren: AuthenticatedTicketsRouteChildren = {
  AuthenticatedTicketsTicketIdRoute: AuthenticatedTicketsTicketIdRoute,
  AuthenticatedTicketsNewRoute: AuthenticatedTicketsNewRoute,
  AuthenticatedTicketsIndexRoute: AuthenticatedTicketsIndexRoute,
  AuthenticatedTicketsAutomationsIndexRoute:
    AuthenticatedTicketsAutomationsIndexRoute,
  AuthenticatedTicketsInboxIndexRoute: AuthenticatedTicketsInboxIndexRoute,
  AuthenticatedTicketsKnowledgeBaseIndexRoute:
    AuthenticatedTicketsKnowledgeBaseIndexRoute,
  AuthenticatedTicketsSettingsIndexRoute:
    AuthenticatedTicketsSettingsIndexRoute,
  AuthenticatedTicketsStatsIndexRoute: AuthenticatedTicketsStatsIndexRoute,
}

const AuthenticatedTicketsRouteWithChildren =
  AuthenticatedTicketsRoute._addFileChildren(AuthenticatedTicketsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRouteWithChildren
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocsRoute: typeof AuthenticatedDocsRouteWithChildren
  AuthenticatedHrRoute: typeof AuthenticatedHrRouteWithChildren
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRouteWithChildren
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedTicketsRoute: typeof AuthenticatedTicketsRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRouteWithChildren,
  AuthenticatedCrmRoute: AuthenticatedCrmRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocsRoute: AuthenticatedDocsRouteWithChildren,
  AuthenticatedHrRoute: AuthenticatedHrRouteWithChildren,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRouteWithChildren,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedTicketsRoute: AuthenticatedTicketsRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ClientPortalTokenRoute: ClientPortalTokenRoute,
  ClientPortalIndexRoute: ClientPortalIndexRoute,
  ClientPortalProjectProjectIdIndexRoute:
    ClientPortalProjectProjectIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
