// ===========================================
// DOCKER CONFIGURATION GENERATOR
// ===========================================

import type { Organization, DockerConfig } from './types'

export function generateDockerConfig(org: Organization): DockerConfig {
  const composeFile = generateDockerCompose(org)
  const envFile = generateEnvFile(org)
  const initSql = generateInitSql(org)

  return { composeFile, envFile, initSql }
}

function generateDockerCompose(org: Organization): string {
  return `# Docker Compose for ${org.name}
# Generated by Sedona Admin Console

version: '3.8'

services:
  # PostgreSQL Database
  db-${org.slug}:
    image: postgres:16-alpine
    container_name: sedona-db-${org.slug}
    restart: unless-stopped
    environment:
      POSTGRES_USER: sedona
      POSTGRES_PASSWORD: \${DB_PASSWORD}
      POSTGRES_DB: sedona_${org.slug}
    volumes:
      - sedona-db-${org.slug}:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${org.port + 5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sedona -d sedona_${org.slug}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Sedona Web Application
  app-${org.slug}:
    image: sedona/web:latest
    container_name: sedona-app-${org.slug}
    restart: unless-stopped
    depends_on:
      db-${org.slug}:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://sedona:\${DB_PASSWORD}@db-${org.slug}:5432/sedona_${org.slug}
      - VITE_SUPABASE_URL=\${SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=\${SUPABASE_ANON_KEY}
      - ORG_ID=${org.id}
      - ORG_NAME=${org.name}
      - ORG_SLUG=${org.slug}
      - ORG_PLAN=${org.plan}
    ports:
      - "${org.port}:3000"

volumes:
  sedona-db-${org.slug}:
    name: sedona-db-${org.slug}

networks:
  default:
    name: sedona-${org.slug}
`
}

function generateEnvFile(org: Organization): string {
  const dbPassword = generateSecurePassword()

  return `# Environment variables for ${org.name}
# Generated by Sedona Admin Console

# Database
DB_PASSWORD=${dbPassword}

# Supabase (optional - for additional features)
SUPABASE_URL=
SUPABASE_ANON_KEY=

# Organization
ORG_ID=${org.id}
ORG_NAME=${org.name}
ORG_SLUG=${org.slug}
ORG_PLAN=${org.plan}

# Admin credentials (first user)
ADMIN_EMAIL=${org.adminEmail}
ADMIN_PASSWORD=${org.adminPassword}
`
}

function generateInitSql(org: Organization): string {
  return `-- Database initialization for ${org.name}
-- Generated by Sedona Admin Console

-- Create organization
INSERT INTO organizations (id, name, slug, subscription_plan, subscription_status, created_at)
VALUES (
  '${org.id}',
  '${org.name}',
  '${org.slug}',
  '${org.plan.toLowerCase()}',
  'active',
  NOW()
);

-- Create admin user
INSERT INTO users (id, name, email, email_verified, created_at, updated_at)
VALUES (
  gen_random_uuid(),
  'Administrateur',
  '${org.adminEmail}',
  true,
  NOW(),
  NOW()
);

-- Create admin employee linked to user
INSERT INTO hr_employees (
  id,
  organization_id,
  first_name,
  last_name,
  email,
  role,
  status,
  created_at
)
SELECT
  gen_random_uuid(),
  '${org.id}',
  'Admin',
  '${org.name}',
  '${org.adminEmail}',
  'owner',
  'active',
  NOW();

-- Note: Password hash should be generated properly in production
-- This is a placeholder for the admin account setup
`
}

function generateSecurePassword(): string {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%'
  let password = ''
  for (let i = 0; i < 24; i++) {
    password += chars.charAt(Math.floor(Math.random() * chars.length))
  }
  return password
}

export function generateDeployScript(org: Organization): string {
  return `#!/bin/bash
# Deployment script for ${org.name}
# Generated by Sedona Admin Console

set -e

DEPLOY_DIR="./deployments/${org.slug}"

echo "Creating deployment directory..."
mkdir -p $DEPLOY_DIR

echo "Copying configuration files..."
# Copy docker-compose.yml, .env, and init.sql to $DEPLOY_DIR

echo "Starting services..."
cd $DEPLOY_DIR
docker-compose up -d

echo ""
echo "==================================="
echo "  ${org.name} deployed successfully!"
echo "==================================="
echo ""
echo "  URL: http://localhost:${org.port}"
echo "  Admin: ${org.adminEmail}"
echo ""
`
}
